name: Tests

on:
  pull_request:

concurrency:
  group: ci-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-full:
    name: Full
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Cache Builds
        uses: Swatinem/rust-cache@v2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        run: cargo test --no-run --all-features
      - name: Test
        run: cargo test --all-features
  test-minimal:
    name: Min
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - name: Cache Builds
        uses: Swatinem/rust-cache@v2
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile
        run: cargo test --no-run --no-default-features
      - name: Test
        run: cargo test --no-default-features
